# Generated by Django 5.1.6 on 2025-02-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_tbl_ksbecomplainttype_tbl_muncipalitycomplainttype_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_ksbecomplainttype',
            new_name='tbl_ksebcomplainttype',
        ),
    ]
