# Generated by Django 5.1.6 on 2025-02-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_rename_tbl_ksbecomplainttype_tbl_ksebcomplainttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_ksebrequesttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_mvdrequesttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(max_length=50)),
            ],
        ),
    ]
