# Generated by Django 5.1.6 on 2025-02-09 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_publicpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_details', models.CharField(max_length=100)),
                ('post_file', models.URLField()),
                ('post_date', models.DateField(auto_now_add=True)),
                ('kseb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_kseb')),
                ('muncipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_muncipality')),
                ('mvd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_mvd')),
                ('pwd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_pwd')),
            ],
        ),
    ]
