# Generated by Django 5.1.6 on 2025-02-21 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
        ('KSEB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_publicpost',
            name='kseb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_kseb'),
        ),
        migrations.AlterField(
            model_name='tbl_publicpost',
            name='muncipality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_muncipality'),
        ),
        migrations.AlterField(
            model_name='tbl_publicpost',
            name='mvd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_mvd'),
        ),
        migrations.AlterField(
            model_name='tbl_publicpost',
            name='pwd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_pwd'),
        ),
    ]
