# Generated by Django 5.1.6 on 2025-02-27 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MVD', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_updates',
        ),
    ]
