# Generated by Django 5.1.6 on 2025-02-09 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_kseb',
            fields=[
                ('kseb_id', models.TextField(editable=False, primary_key=True, serialize=False)),
                ('kseb_name', models.CharField(max_length=30)),
                ('kseb_email', models.CharField(max_length=40)),
                ('kseb_contact', models.CharField(max_length=30)),
                ('kseb_address', models.CharField(max_length=80)),
                ('kseb_proof', models.URLField()),
                ('kseb_password', models.CharField(max_length=30)),
                ('kseb_status', models.IntegerField(default=0)),
                ('localplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_localplace')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_muncipality',
            fields=[
                ('mun_id', models.TextField(editable=False, primary_key=True, serialize=False)),
                ('mun_name', models.CharField(max_length=30)),
                ('mun_email', models.CharField(max_length=40)),
                ('mun_contact', models.CharField(max_length=30)),
                ('mun_address', models.CharField(max_length=80)),
                ('mun_proof', models.URLField()),
                ('mun_password', models.CharField(max_length=30)),
                ('mun_status', models.IntegerField(default=0)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_district')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_mvd',
            fields=[
                ('mvd_id', models.TextField(editable=False, primary_key=True, serialize=False)),
                ('mvd_name', models.CharField(max_length=30)),
                ('mvd_email', models.CharField(max_length=40)),
                ('mvd_contact', models.CharField(max_length=30)),
                ('mvd_address', models.CharField(max_length=80)),
                ('mvd_proof', models.URLField()),
                ('mvd_password', models.CharField(max_length=30)),
                ('mvd_status', models.IntegerField(default=0)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_district')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_pwd',
            fields=[
                ('pwd_id', models.TextField(editable=False, primary_key=True, serialize=False)),
                ('pwd_name', models.CharField(max_length=30)),
                ('pwd_email', models.CharField(max_length=40)),
                ('pwd_contact', models.CharField(max_length=30)),
                ('pwd_address', models.CharField(max_length=80)),
                ('pwd_proof', models.URLField()),
                ('pwd_password', models.CharField(max_length=30)),
                ('pwd_status', models.IntegerField(default=0)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_district')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('user_id', models.TextField(editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('user_email', models.CharField(max_length=40)),
                ('user_contact', models.CharField(max_length=30)),
                ('user_address', models.CharField(max_length=80)),
                ('user_photo', models.URLField()),
                ('user_password', models.CharField(max_length=30)),
                ('user_status', models.IntegerField(default=0)),
                ('localplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_localplace')),
                ('muncipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_muncipality')),
            ],
        ),
    ]
