# Generated by Django 5.1.6 on 2025-04-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user',
            name='user_photo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tbl_user',
            name='user_status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
