# Generated by Django 5.1.6 on 2025-02-20 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_rename_tbl_ksbecomplainttype_tbl_ksebcomplainttype'),
        ('User', '0002_tbl_complaint_complainttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_complaint',
            old_name='complainttype',
            new_name='muncomplainttype',
        ),
        migrations.AddField(
            model_name='tbl_complaint',
            name='ksebcomplainttype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_ksebcomplainttype'),
        ),
        migrations.AddField(
            model_name='tbl_complaint',
            name='mvdcomplainttype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_mvdcomplainttype'),
        ),
        migrations.AddField(
            model_name='tbl_complaint',
            name='pwdcomplainttype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_pwdcomplainttype'),
        ),
    ]
