# Generated by Django 5.1.6 on 2025-02-21 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KSEB', '0002_alter_tbl_publicpost_kseb_and_more'),
        ('User', '0003_rename_complainttype_tbl_complaint_muncomplainttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_like',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='KSEB.tbl_publicpost'),
        ),
        migrations.AlterField(
            model_name='tbl_like',
            name='complaint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.tbl_complaint'),
        ),
    ]
