# Generated by Django 5.1.6 on 2025-02-27 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_ksebrequesttype_tbl_mvdrequesttype'),
        ('User', '0004_tbl_like_post_alter_tbl_like_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_request',
            name='ksebrequesttype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_ksebrequesttype'),
        ),
        migrations.AddField(
            model_name='tbl_request',
            name='mvdrequesttype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_mvdrequesttype'),
        ),
    ]
