# Generated by Django 5.1.6 on 2025-02-27 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_tbl_request_ksebrequesttype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_request',
            name='request_title',
        ),
    ]
