# Generated by Django 5.1.6 on 2025-02-27 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_remove_tbl_request_request_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_request',
        ),
    ]
