# Generated by Django 5.1.6 on 2025-02-27 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_ksebrequesttype_tbl_mvdrequesttype'),
        ('Guest', '0001_initial'),
        ('User', '0007_delete_tbl_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_content', models.CharField(max_length=200)),
                ('request_response', models.CharField(max_length=200)),
                ('request_status', models.IntegerField(default=0)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('request_photo', models.TextField()),
                ('kseb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_kseb')),
                ('ksebrequesttype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_ksebrequesttype')),
                ('muncipality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_muncipality')),
                ('mvd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_mvd')),
                ('mvdrequesttype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_mvdrequesttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
